
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("b9b26a36-391e-442a-b3a1-b99a7b206036")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("StatesModel", "FK_County_State", "State", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(State), "County", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(County), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class StatesEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new StatesEntities object using the connection string found in the 'StatesEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=StatesEntities", "StatesEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new StatesEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "StatesEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new StatesEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "StatesEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Counties() As ObjectSet(Of County)
        Get
            If (_Counties Is Nothing) Then
                _Counties = MyBase.CreateObjectSet(Of County)("Counties")
            End If
            Return _Counties
        End Get
    End Property

    Private _Counties As ObjectSet(Of County)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property States() As ObjectSet(Of State)
        Get
            If (_States Is Nothing) Then
                _States = MyBase.CreateObjectSet(Of State)("States")
            End If
            Return _States
        End Get
    End Property

    Private _States As ObjectSet(Of State)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Counties EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCounties(ByVal county As County)
        MyBase.AddObject("Counties", county)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the States EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToStates(ByVal state As State)
        MyBase.AddObject("States", state)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="StatesModel", Name:="County")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class County
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new County object.
    ''' </summary>
    ''' <param name="countyID">Initial value of the countyID property.</param>
    ''' <param name="stateID">Initial value of the stateID property.</param>
    Public Shared Function CreateCounty(countyID As Global.System.Int32, stateID As Global.System.Int32) As County
        Dim county as County = New County
        county.countyID = countyID
        county.stateID = stateID
        Return county
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property countyID() As Global.System.Int32
        Get
            Return _countyID
        End Get
        Set
            If (_countyID <> Value) Then
                OncountyIDChanging(value)
                ReportPropertyChanging("countyID")
                _countyID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("countyID")
                OncountyIDChanged()
            End If
        End Set
    End Property

    Private _countyID As Global.System.Int32
    Private Partial Sub OncountyIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OncountyIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property stateID() As Global.System.Int32
        Get
            Return _stateID
        End Get
        Set
            OnstateIDChanging(value)
            ReportPropertyChanging("stateID")
            _stateID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("stateID")
            OnstateIDChanged()
        End Set
    End Property

    Private _stateID As Global.System.Int32
    Private Partial Sub OnstateIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnstateIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property countyName() As Global.System.String
        Get
            Return _countyName
        End Get
        Set
            OncountyNameChanging(value)
            ReportPropertyChanging("countyName")
            _countyName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("countyName")
            OncountyNameChanged()
        End Set
    End Property

    Private _countyName As Global.System.String
    Private Partial Sub OncountyNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncountyNameChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("StatesModel", "FK_County_State", "State")>
    Public Property State() As State
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of State)("StatesModel.FK_County_State", "State").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of State)("StatesModel.FK_County_State", "State").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property StateReference() As EntityReference(Of State)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of State)("StatesModel.FK_County_State", "State")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of State)("StatesModel.FK_County_State", "State", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="StatesModel", Name:="State")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class State
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new State object.
    ''' </summary>
    ''' <param name="stateID">Initial value of the stateID property.</param>
    ''' <param name="stateName">Initial value of the stateName property.</param>
    ''' <param name="stateAbbr">Initial value of the stateAbbr property.</param>
    Public Shared Function CreateState(stateID As Global.System.Int32, stateName As Global.System.String, stateAbbr As Global.System.String) As State
        Dim state as State = New State
        state.stateID = stateID
        state.stateName = stateName
        state.stateAbbr = stateAbbr
        Return state
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property stateID() As Global.System.Int32
        Get
            Return _stateID
        End Get
        Set
            If (_stateID <> Value) Then
                OnstateIDChanging(value)
                ReportPropertyChanging("stateID")
                _stateID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("stateID")
                OnstateIDChanged()
            End If
        End Set
    End Property

    Private _stateID As Global.System.Int32
    Private Partial Sub OnstateIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnstateIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property stateName() As Global.System.String
        Get
            Return _stateName
        End Get
        Set
            OnstateNameChanging(value)
            ReportPropertyChanging("stateName")
            _stateName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("stateName")
            OnstateNameChanged()
        End Set
    End Property

    Private _stateName As Global.System.String
    Private Partial Sub OnstateNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property stateAbbr() As Global.System.String
        Get
            Return _stateAbbr
        End Get
        Set
            OnstateAbbrChanging(value)
            ReportPropertyChanging("stateAbbr")
            _stateAbbr = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("stateAbbr")
            OnstateAbbrChanged()
        End Set
    End Property

    Private _stateAbbr As Global.System.String
    Private Partial Sub OnstateAbbrChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateAbbrChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stateCapital() As Global.System.String
        Get
            Return _stateCapital
        End Get
        Set
            OnstateCapitalChanging(value)
            ReportPropertyChanging("stateCapital")
            _stateCapital = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("stateCapital")
            OnstateCapitalChanged()
        End Set
    End Property

    Private _stateCapital As Global.System.String
    Private Partial Sub OnstateCapitalChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateCapitalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stateTree() As Global.System.String
        Get
            Return _stateTree
        End Get
        Set
            OnstateTreeChanging(value)
            ReportPropertyChanging("stateTree")
            _stateTree = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("stateTree")
            OnstateTreeChanged()
        End Set
    End Property

    Private _stateTree As Global.System.String
    Private Partial Sub OnstateTreeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateTreeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stateFlower() As Global.System.String
        Get
            Return _stateFlower
        End Get
        Set
            OnstateFlowerChanging(value)
            ReportPropertyChanging("stateFlower")
            _stateFlower = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("stateFlower")
            OnstateFlowerChanged()
        End Set
    End Property

    Private _stateFlower As Global.System.String
    Private Partial Sub OnstateFlowerChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateFlowerChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stateBird() As Global.System.String
        Get
            Return _stateBird
        End Get
        Set
            OnstateBirdChanging(value)
            ReportPropertyChanging("stateBird")
            _stateBird = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("stateBird")
            OnstateBirdChanged()
        End Set
    End Property

    Private _stateBird As Global.System.String
    Private Partial Sub OnstateBirdChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateBirdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stateRegion() As Global.System.String
        Get
            Return _stateRegion
        End Get
        Set
            OnstateRegionChanging(value)
            ReportPropertyChanging("stateRegion")
            _stateRegion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("stateRegion")
            OnstateRegionChanged()
        End Set
    End Property

    Private _stateRegion As Global.System.String
    Private Partial Sub OnstateRegionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateRegionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stateImageFlag() As Global.System.String
        Get
            Return _stateImageFlag
        End Get
        Set
            OnstateImageFlagChanging(value)
            ReportPropertyChanging("stateImageFlag")
            _stateImageFlag = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("stateImageFlag")
            OnstateImageFlagChanged()
        End Set
    End Property

    Private _stateImageFlag As Global.System.String
    Private Partial Sub OnstateImageFlagChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateImageFlagChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stateImageSeal() As Global.System.String
        Get
            Return _stateImageSeal
        End Get
        Set
            OnstateImageSealChanging(value)
            ReportPropertyChanging("stateImageSeal")
            _stateImageSeal = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("stateImageSeal")
            OnstateImageSealChanged()
        End Set
    End Property

    Private _stateImageSeal As Global.System.String
    Private Partial Sub OnstateImageSealChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateImageSealChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("StatesModel", "FK_County_State", "County")>
     Public Property Counties() As EntityCollection(Of County)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of County)("StatesModel.FK_County_State", "County")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of County)("StatesModel.FK_County_State", "County", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

